name: home
domains:
  - jtalk.me
basePath: ""
staging: false

atom:
  urlBasePath: /blog/articles

ui:
  type: ui
  name: home-ui
  bugsnag:
    key:
  service:
    port: 80
  deployment:
    port: 80
    image:
      name: jtalk/home-ui
    replicas: 2
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    affinity:
      weight: 100
      topologyKey: kubernetes.io/hostname
    probes:
      startup:
        failureThreshold: 15
        periodSeconds: 1
        timeoutSeconds: 1
      liveness:
        path: /api/health
        failureThreshold: 2
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
    resources:
      limits:
        memory: 150Mi
      requests:
        cpu: 100m
        memory: 150Mi

api:
  type: api
  name: home-api
  basePath: /api
  session:
    secret: ""
    maxAge: 10m
  cors:
    localhostPort: 8070
  service:
    port: 80
  deployment:
    port: 8090
    image:
      name: jtalk/home-api
    replicas: 2
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 50%
    affinity:
      weight: 100
      topologyKey: kubernetes.io/hostname
    probes:
      startup:
        failureThreshold: 15
        periodSeconds: 1
        timeoutSeconds: 1
      liveness:
        path: /health
        failureThreshold: 1
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      readiness:
        path: /ready
        failureThreshold: 1
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
    resources:
      limits:
        memory: 80Mi
      requests:
        cpu: 100m
        memory: 20Mi

database:
  secret:
    name: database
    urlKey: DATABASE_CONNECTION
  url: ""
  migration:
    name: database-migration
    deadline:
      seconds: 60
    image:
      name: jtalk/home-dbmigrate
  backup:
    name: database-backup
    schedule: "0 2 2 * *"
    image:
      name: jtalk/home-dbbackup
    aws:
      bucket: ""
      key:
        id: ""
        secret: ""

stagingCleanup:
  name: staging-cleanup
  schedule: "0 1 * * *"
  account:
    name: staging-cleanup
