apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ quote .Values.name }}
    type: {{ quote .Values.ui.type }}
  name: {{ quote .Values.ui.name }}
spec:
  replicas: {{ .Values.ui.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ quote .Values.name }}
      type: {{ quote .Values.ui.type }}
  strategy:
    {{- dict "type" "RollingUpdate" "rollingUpdate" .Values.ui.deployment.rollingUpdate | toYaml | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ quote .Values.name }}
        type: {{ quote .Values.ui.type }}
    spec:
      {{- include "jtalk.me.deployment.affinity" (merge (dict) .Values.ui.deployment.affinity (dict "name" .Values.name "type" .Values.ui.type)) | indent 6 }}
      containers:
        - name: {{ quote .Values.ui.name }}
          image: {{ printf "%s:%s" .Values.ui.deployment.image.name .Chart.AppVersion | quote }}
          envFrom:
            - configMapRef:
                name: {{ quote .Values.ui.name }}
                optional: no
          {{- include "jtalk.me.container.probes" .Values.ui.deployment | indent 10 }}
          ports:
            - containerPort: {{ .Values.ui.deployment.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.ui.deployment.resources | nindent 12 }}

