apiVersion: v1
kind: Service
metadata:
  name: {{ quote .Values.ui.name }}
  labels:
    app: {{ quote .Values.name }}
    type: {{ quote .Values.ui.type }}
spec:
  selector:
    app: {{ quote .Values.name }}
    type: {{ quote .Values.ui.type }}
  {{- include "jtalk.me.service.ports" .Values.ui | indent 2 }}
