apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: backup
spec:
  schedule: "0 2 * 2 *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: home-backup
            image: jtalk/home-dbbackup:[[IMAGE_TAG]]
            env:
              - name: BUCKET_PATH
                value: jtalk.me-backup/live
              - name: MONGO_URL
                valueFrom:
                  secretKeyRef:
                    name: home-api
                    key: mongo-uri
              - name: AWS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    name: aws-creds
                    key: key-id
              - name: AWS_KEY
                valueFrom:
                  secretKeyRef:
                    name: aws-creds
                    key: key
          restartPolicy: Never
