apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ quote .Values.api.name }}
data:
  {{- $cors := list }}
  {{- range $index, $domain := .Values.domains }}
    {{- $cors = append $cors (printf "https://%s" $domain) }}
  {{- end }}
  {{- if and .Values.staging .Values.api.cors.localhostPort }}
    {{- $cors = append $cors (printf "http://localhost:%.0f" .Values.api.cors.localhostPort) }}
  {{- end }}
  CORS_ORIGINS: {{ join "," $cors | quote }}
  ATOM_ARTICLE_URL_PREFIX: {{ printf "https://%s%s%s" (mustFirst .Values.domains) .Values.basePath .Values.atom.urlBasePath | quote }}
  AUTH_MAX_AGE: {{ required "Session max age is required" .Values.api.session.maxAge | quote }}