apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ quote .Values.name }}
    type: {{ quote .Values.api.type }}
  name: {{ quote .Values.api.name }}
spec:
  replicas: {{ .Values.api.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ quote .Values.name }}
      type: {{ quote .Values.api.type }}
  strategy:
    {{- dict "type" "RollingUpdate" "rollingUpdate" .Values.api.deployment.rollingUpdate | toYaml | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ quote .Values.name }}
        type: {{ quote .Values.api.type }}
    spec:
      {{- include "jtalk.me.deployment.affinity" (merge (dict) .Values.api.deployment.affinity (dict "name" .Values.name "type" .Values.api.type)) | indent 6 }}
      containers:
        - name: {{ quote .Values.api.name }}
          image: {{- include "jtalk.me.container.image" .Values.api.deployment.image | quote | indent 1 }}
          env:
            - name: HTTP_PORT
              value: {{ quote .Values.api.deployment.port }}
          envFrom:
            - configMapRef:
                name: {{ quote .Values.api.name }}
                optional: no
            - secretRef:
                name: {{ quote .Values.api.name }}
                optional: no
            - secretRef:
                name: {{ quote .Values.database.secret.name }}
                optional: no
          {{- include "jtalk.me.container.probes" .Values.api.deployment | indent 10 }}
          ports:
            - containerPort: {{ .Values.api.deployment.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.api.deployment.resources | nindent 12 }}

