apiVersion: v1
kind: Secret
metadata:
  name: {{ quote .Values.api.name }}
type: Opaque
stringData:
  APPLICATION_SECRET: {{ required "API secret is required" .Values.api.encryption.secret | quote }}
  APP_SETUP_ENABLED: {{ quote .Values.api.initialSetup.enabled }}
  {{- if .Values.api.initialSetup.enabled }}
  APP_SETUP_DEFAULT_PASSWORD: {{ required "Initial password is required when initial setup is enabled" .Values.api.initialSetup.initialPassword | quote }}
  {{- end }}
