{{- if or .Values.database.backup.aws.key.id .Values.database.backup.aws.bucket }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ quote .Values.database.backup.name }}
spec:
  schedule: {{ quote .Values.database.backup.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ quote .Values.database.backup.name }}
            image: {{ printf "%s:%s" .Values.database.backup.image.name .Chart.AppVersion | quote }}
            envFrom:
            - secretRef: 
                name: {{ quote .Values.database.backup.name }}
                optional: no
            env:
            - name: BUCKET_PATH
              {{- $pathInsideBucket := ternary "staging" "live" .Values.staging }}
              value: {{ printf "%s/%s" (required "AWS bucket is required" .Values.database.backup.aws.bucket) $pathInsideBucket | quote }}
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: {{ quote .Values.database.secret.name }}
                  key: {{ quote .Values.database.secret.urlKey }}
          restartPolicy: Never
{{- end }}