nodeLinker: pnp
pnpMode: strict

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@ojkelly/plugin-build.cjs
    spec: "https://yarn.build/latest/build"
  - path: .yarn/plugins/@ojkelly/plugin-bundle.cjs
    spec: "https://yarn.build/latest/bundle"

packageExtensions:
  react-dev-utils@*:
    peerDependencies:
      typescript: "*"
      webpack: "*"
  eslint-config-react-app@*:
    peerDependencies:
      "@babel/plugin-syntax-flow": "*"
      "@babel/plugin-transform-react-jsx": "*"
