apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: staging-cleanup
  namespace: home-staging
rules:
- apiGroups:
  - apps
  - extensions
  resources:
  - deployments
  verbs:
  - get
- apiGroups:
  - apps
  - extensions
  resources:
  - deployments/scale
  verbs:
  - patch
