apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: staging-cleanup
  namespace: home-staging
spec:
  schedule: "0 1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: staging-cleanup
          automountServiceAccountToken: yes
          containers:
          - name: staging-cleanup
            image: bitnami/kubectl:1.16
            command: [sh]
            args:
            - -c
            - |
              kubectl scale deployment home-api --replicas=0;
              kubectl scale deployment home-ui --replicas=0;
          restartPolicy: Never
