FROM node:13-alpine
COPY ./ ./
RUN npm install
ENTRYPOINT ["npm", "run"]
CMD ["status"]



-H "X-Athena-Legacy-User: alextest" \
-H "Accept-Encoding: gzip, deflate, br" \
-H "Accept: application/json, text/plain, */*" \
-H "X-Athena-Host-App-Id: efset-widget" \
-H "Pragma: no-cache" \
-H "Origin: https://cdn.efset.cn" \
-H "Accept-Encoding: gzip, deflate, br" \
-H "Accept-Language: Accept-Language" \
-H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36" \
-H "Cache-Control: no-cache" \
-H "Connection: keep-alive" \



-H "X-Athena-Legacy-User: testalex" \
-H "Origin: https://cdn.efset.org" \
-H "Accept-Encoding: gzip, deflate, br" \
-H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36" \
-H "Accept: application/json, text/plain, */*" \
-H "X-Athena-Host-App-Id: efset-widget" \
-H "Pragma: no-cache" \
