version: '3'

services:
  mongo:
    build: mongo-dbinit
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: home

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo