services:
  mongo:
    build: mongo-dbinit
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: home

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
      - migrator

  migrator:
    image: migrate-dev
    build:
      context: ../home2-dbmigrate
    command: up:wait
    environment:
      DATABASE_URL: mongodb://mongo:27017
      DATABASE_URL_WAIT_ON: tcp://mongo:27017
      DATABASE_NAME: home
