apiVersion: batch/v1
kind: Job
metadata:
  name: home-migrate-db
  namespace: home
spec:
  activeDeadlineSeconds: 60
  template:
    spec:
      containers:
        - name: migrate-db
          image: jtalk/home-dbmigrate:[[IMAGE_TAG]]
          args: ["up"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: home-api
                  key: mongo-uri
            - name: DATABASE_NAME
              value: home
      restartPolicy: Never
