{{- define "jtalk.me.ingress.tls.host" }}
- hosts:
  - {{ .domain | quote }}
  secretName: {{ printf "%s-certificate" .domain | quote }}
{{- end }}

{{- define "jtalk.me.ingress.each-domain" }}
  {{- range $domain := .domains }}
    {{- include $.each (merge (dict) $ (dict "domain" $domain)) | indent 2}}
  {{- end }}
{{- end }}

{{- define "jtalk.me.ingress.tls" }}
tls:
  {{- include "jtalk.me.ingress.each-domain" (merge (dict) . (dict "each" "jtalk.me.ingress.tls.host")) | indent 2 }}
{{- end }}