{{- define "jtalk.me.ingress.annotations" }}
annotations:
  kubernetes.io/ingress.class: nginx
  cert-manager.io/cluster-issuer: letsencrypt
  {{- if .basePath }}
  nginx.ingress.kubernetes.io/rewrite-target: /$1
  {{- end }}
{{- end }}