{{- define "jtalk.me.container.resources" }}
{{- if . }}
resources:
  {{- if .limits }}
  limits:
    {{- if .limits.cpu }}
    cpu: {{ quote .limits.cpu }}
    {{- end }}
    {{- if .limits.memory }}
    memory: {{ quote .limits.memory }}
    {{- end }}
  {{- end }}
  {{- if or .limits .requests }}
  requests:
    {{- $cpuRequest := default .limits.cpu .requests.cpu -}}
    {{- $memoryRequest := default .limits.memory .requests.memory -}}
    {{- if $cpuRequest }}
    cpu: {{ $cpuRequest | quote }}
    {{- end }}
    {{- if $memoryRequest }}
    memory: {{ $memoryRequest | quote }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}