apiVersion: v1
kind: ConfigMap
namespace: home-staging
metadata:
  name: home-api
  namespace: home-staging
data:
  "CORS_ALLOWED_ORIGINS.0": "https://staging.jtalk.me"
  "CORS_ALLOWED_ORIGINS.1": "http://localhost:8070"
  ATOM_BASE_URL: "https://staging.jtalk.me/atom.xml"
  ATOM_ENTRY_BASE_URL: "https://staging.jtalk.me/blog/articles"