apiVersion: v1
kind: Service
metadata:
  name: home-api
  labels:
    app: home
    type: api
spec:
  selector:
    app: home
    type: api
  ports:
    - name: http
      port: 80
      targetPort: 8080