apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-ui
  namespace: home-staging
  labels:
    app: home-ui
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
    - hosts:
        - staging.jtalk.me
      secretName: home-staging-certificate
  rules:
    - host: staging.jtalk.me
      http:
        paths:
          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: home-ui
                port:
                  number: 80
