apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Values.database.migration.name }}-{{ .Values.database.migration.image.version }}"
spec:
  activeDeadlineSeconds: {{ .Values.database.migration.deadline.seconds }}
  template:
    spec:
      containers:
        - name: "{{ .Values.database.migration.name }}-{{ .Values.database.migration.image.version }}"
          image: {{- include "jtalk.me.container.image" .Values.database.migration.image | quote | indent 1 }}
          args: ["up"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ quote .Values.database.secret.name }}
                  key: {{ quote .Values.database.secret.urlKey }}
            - name: DATABASE_NAME
              value: {{ splitList "/" .Values.database.url | mustLast | quote }}
      restartPolicy: Never
