apiVersion: v1
kind: Secret
metadata:
  name: {{ quote .Values.database.secret.name }}
type: Opaque
stringData:
  {{ quote .Values.database.secret.urlKey }}: {{ required "Database URL is required" .Values.database.url | quote }}
