apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: home
    type: api
  name: home-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home
      type: api
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: home
        type: api
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: home
                    type: api
                topologyKey: kubernetes.io/hostname
              weight: 100
      containers:
        - name: home-api
          image: jtalk/home-api:[[IMAGE_TAG]]
          env:
            - name: HTTP_PORT
              value: "8080"
            - name: APPLICATION_SECRET
              valueFrom:
                secretKeyRef:
                  name: home-api
                  key: application-secret
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: home-api
                  key: mongo-uri
          envFrom:
            - configMapRef:
                name: home-api
                optional: no
          startupProbe:
            httpGet:
              path: /status
              port: 8080
              scheme: HTTP
            failureThreshold: 15
            periodSeconds: 1
            timeoutSeconds: 1
          livenessProbe:
            failureThreshold: 1
            httpGet:
              path: /status
              port: 8080
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 1
            httpGet:
              path: /status/ready
              port: 8080
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              memory: 400Mi
            requests:
              cpu: 100m
              memory: 400Mi
