apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: home
    type: api
  name: home-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home
      type: api
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: home
        type: api
    spec:
      containers:
        - name: home-api
          image: jtalk/home-api:[[IMAGE_TAG]]
          env:
            - name: HTTP_PORT
              value: "8080"
            - name: APPLICATION_SECRET
              valueFrom:
                secretKeyRef:
                  name: home-api
                  key: application-secret
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: home-api
                  key: mongo-uri
          startupProbe:
            httpGet:
              path: /status
              port: 8080
              scheme: HTTP
            periodSeconds: 1
            timeoutSeconds: 15
          livenessProbe:
            failureThreshold: 2
            httpGet:
              path: /status
              port: 8080
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
            initialDelaySeconds: 15
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              memory: 400M
            requests:
              cpu: 10m
              memory: 300M
