apiVersion: batch/v1
kind: Job
metadata:
  name: {{ quote .Values.database.migration.name }}
spec:
  activeDeadlineSeconds: {{ .Values.database.migration.deadline.seconds }}
  template:
    spec:
      containers:
        - name: {{ quote .Values.database.migration.name }}
          image: "{{ .Values.database.backup.image.name }}:{{ .Values.database.backup.image.version }}"
          args: ["up"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ quote .Values.database.secret.name }}
                  key: {{ quote .Values.database.secret.urlKey }}
            - name: DATABASE_NAME
              value: {{ quote .Values.database.name }}
      restartPolicy: Never
