services:
  api:
    image: api
    container_name: api
    build:
      context: .
    ports:
      - "8090"
    depends_on:
      - database
    environment:
      DATABASE_CONNECTION: mongodb://database:27017/home
      AUTH_KEY: bGthc2pkaGdrYXNkaGdoZGFzamtnaGpka3NoZ2FrbGpzZGhnamtsZGhzZwo=
      AUTH_MAX_AGE: 60s
      CORS_ORIGINS: http://localhost:8070
      ATOM_ARTICLE_URL_PREFIX: http://localhost:8070/blog/articles
  database:
    container_name: database
    extends:
      file: ../home2-dev/docker-compose.yml
      service: mongo
  database_migrator:
    container_name: migrator
    extends:
      file: ../home2-dev/docker-compose.yml
      service: migrator
  test:
    image: integration-test
    build:
      context: .
      target: integration-test
    depends_on:
      - api
      - database
      - database_migrator
    environment:
      TEST_BASE_URL: http://api:8090