apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ quote .Values.database.backup.name }}
spec:
  schedule: {{ quote .Values.database.backup.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ quote .Values.database.backup.name }}
            image: "{{ .Values.database.backup.image.name }}:{{ .Values.database.backup.image.version }}"
            envFrom:
              secretRef: 
                name: {{ quote .Values.database.backup.name }}
                optional: no
            env:
              - name: BUCKET_PATH
                value: {{ printf "%s/%s" (required "AWS bucket is required" .Values.database.backup.aws.bucket) .Values.environment | quote }}
              - name: MONGO_URL
                valueFrom:
                  secretKeyRef:
                    name: {{ quote .Values.database.secret.name }}
                    key: {{ quote .Values.database.secret.urlKey }}
          restartPolicy: Never
