
apiVersion: v1
kind: Secret
metadata:
  name: {{ quote .Values.database.backup.name }}
type: Opaque
stringData:
  AWS_KEY_ID: {{ required "Backup AWS key ID is required" .Values.database.backup.aws.key.id | quote }}
  AWS_KEY: {{ required "Backup AWS key ID is required" .Values.database.backup.aws.key.secret | quote }}
