apiVersion: v1
kind: ConfigMap
metadata:
  name: home-api
  namespace: home
data:
  "CORS_ALLOWED_ORIGINS.0": "https://jtalk.me"
  ATOM_URL: "https://jtalk.me/atom.xml"
  ATOM_ENTRY_BASE_URL: "https://jtalk.me/blog/articles"