name: Home Deploy

on: [push]

env:
  CI: true
  NODE_VERSION: 13.x

  UI_DOCKER_IMAGE_PREFIX: jtalk/home-ui
  API_DOCKER_IMAGE_PREFIX: jtalk/home-api
  DBMIGRATE_DOCKER_IMAGE_PREFIX: jtalk/home-dbmigrate
  
jobs:
  build-release-ui:
    name: Build and Release to Docker
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
      REACT_APP_API_LOCATION: /api
    steps:
    - uses: actions/checkout@v1
    - name: Set up Node.JS ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
      
    - name: Test UI
      working-directory: home2-ui
      env:
        CI: true
        NODE_ENV: development
      run: |
        npm ci
        npm test src/
    - name: Build UI
      working-directory: home2-ui
      env:
      run: |
        npm ci
        npm run build
    - name: Build & Push docker
      uses: ./.github/action/docker-build-push
      with:
        tagPrefix: ${UI_DOCKER_IMAGE_PREFIX}
        working-dir: home2-ui
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
#   deploy:
#     name: Deploy to Kubernetes
#     runs-on: ubuntu-latest
#     needs: build-release
#     if: github.ref == 'refs/heads/master'
#     env:
#       KUBE_NS: digito
#     steps:
#       - uses: actions/checkout@v1
#       - name: Load Kubernetes config
#         env:
#           DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DO_TOKEN }}
#         run: |
#           mkdir $HOME/.kube
#           docker run --rm \
#             -e "DIGITALOCEAN_ACCESS_TOKEN=$DIGITALOCEAN_ACCESS_TOKEN" \
#             digitalocean/doctl kubernetes cluster kubeconfig show ${{ secrets.DO_K8S_CLUSTER_NAME }} \
#             > $HOME/.kube/config
#       - name: Deploy to Kubernetes
#         working-directory: digito-ui/deploy
#         run: |
#             # Good ol' kubernetes, still unable to figure image tags out on its own in 2019...
#             # Also all this [[][[][]][[][]] is because Sed is kind of a retard when it comes to brackets.
#             sed -i -- 's/[[][[]IMAGE_TAG[]][]]/${{ github.sha }}/' deployment.yml
#             # Fix namespace
#             kubectl config set-context --current --namespace=$KUBE_NS
#             # It's faster to deploy manually than to be figuring out all the Azure k8s-deploy's
#             # idiosyncrasies one by one tbh.
#             kubectl apply -f deployment.yml
#             kubectl apply -f service.yml
#             kubectl apply -f ingress.yml
#             # Waiting for the rollout
#             kubectl rollout status -w --timeout=1m -f deployment.yml
#   verify:
#     name: Verify deployment
#     runs-on: ubuntu-latest
#     needs: deploy
#     steps:
#       - name: Verify the healthcheck URL
#         run: |
#           curl --fail https://digito.jtalk.me/
        














